on:
  workflow_dispatch:
# on:
#   push:
#     branches:
#       - 'main'
jobs:
  hello_world_job:
    runs-on: self-ubuntu
    environment: DEV
    name: A job to deploy UCD application
    steps:
      - name: Fetch properties file
        id: download_ucd_properties_file  
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ucdproperties
          sparse-checkout-cone-mode: false
      - name: Deploy UCD application
        id: Deploy_MYAPP
        uses: bharathk-github/UrbanCodeDeployAction@vtest-1.23
        with:
          application: 'MYAPP'
          applicationProcess: 'Install'
          environment: 'DEV'
          # properties: '{"prop1":"${{ vars.PROP1 }}", "prop2":"${{ vars.PROP2 }}"}'
          propertiesfile: 'ucdproperties'
          snapshot: 'snapshot-2'
          versions: '[{"version": "TEMP1-JCLA", "component": "MYCOMP"},{"version": "File1","component": "Regular component"},{"version": "file2","component": "Regular component"}]'
          hostname: '${{ secrets.UCD_HOST }}'
          username: '${{ secrets.UCD_USERNAME }}'
          password: '${{ secrets.UCD_PASSWORD }}'
          authToken: '${{ secrets.UCD_AUTHTOKEN }}'

