on:
  workflow_dispatch:
    inputs:
      version-input:
        description: 'Versions to deploy'

jobs:
  hello_world_job:
    runs-on: self-hosted
    name: A job to deploy UCD application
    steps:
      - name: Deploy UCD application
        id: Deploy_MYAPP
        uses: bharathk-github/UrbanCodeDeployAction@v1.21
        with:
          application: 'MYAPP'
          applicationProcess: 'Install'
          environment: 'DEV'
          properties: '{"prop1":"Hello IBM", "prop2":"Hello UCD"}'
          versions: '[{"version": "TEMP1-JCLA", "component": "MYCOMP"},{"version": "File1","component": "Regular component"},{"version": "file2","component": "Regular component"}]'
          hostname: '${{ secrets.UCD_HOST }}'
          username: '${{ secrets.UCD_USERNAME }}'
          password: '${{ secrets.UCD_PASSWORD }}'

