on:
  workflow_dispatch:
jobs:
  hello_world_job:
    runs-on: self-hosted
    environment: DEV
    name: A job to deploy UCD application
    steps:
      - name: Fetch properties file
        id: download_ucd_properties_file  
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ucdproperties
          sparse-checkout-cone-mode: false
      - name: Deploy UCD application
        id: Deploy_MYAPP
        uses: bharathk-github/UrbanCodeDeployAction@v1.30
        with:
          application: 'MYAPP'
          applicationProcess: 'PARTIAL-JCL-DBRM'
          environment: 'DEV'
          propertiesfile: 'ucdproperties'          
          versions: '[{"version": "DIFF-DEPL-TYPE", "component": "MYCOMP"}]'
          hostname: '${{ secrets.UCD_HOST }}'
          port: '8443'
          username: '${{ secrets.UCD_USERNAME }}'
          password: '${{ secrets.UCD_PASSWORD }}'
          authToken: '${{ secrets.UCD_AUTHTOKEN }}'
          disableSSLVerification: 'true'
